### ISSUE TITLE
[Epic] Make FTL13 compatible with Byond 512

### ISSUE THREAD

**Issue by crossedfall** [FTL13/FTL13#3574]
This is a frequent issue that comes up in the coderbus channel, and more recently has been seen as an issue (#3573) in GitHub. It might be time to review the current code and changes to see if it's actually something we can support, and if we even want to support it. There are a number of enhancements in 512 that might benefit us as well, such as the improvements to server security. Current notable concerns would be backwards compatibility and time-to-implement.

## Steps to provide 512 support

- [x] Review the [changelog ](http://www.byond.com/docs/notes/512.html)for breaking changes in the byond compiler/client
- [x] Determine if the changes are substantial for our current codebase
- [x] Review any issues with backwards compatibility
- [x] Determine what (if any) sister codebase PRs can be applied to cut down on duplicate work
- [x] Review/correct compile errors
- [x] Test to ensure basic functionality
- [x] Test for any new bugs & performance degradation/enhancements

#### ~~Current known compiler error~~

Compile errors resolved in #3607 

#### Potential changes to be pulled from the upstream

https://github.com/tgstation/tgstation/pull/32161/files 

#### Remaining issues
Travis does not correctly compile 512

**Comment by MadmanMartian** [comment]
There is just a rogue full stop at the end of an operator. It doesn't do anything in particular, and seems to just be corruption/typo

**Comment by MadmanMartian** [comment]
There was also some variables named filter that needed changing.

**Comment by MadmanMartian** [comment]
https://github.com/tgstation/tgstation/pull/32161/files

**Comment by crossedfall** [comment]
This is ready to be closed once #3617 is merged
